spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/brosWarehouse
    driver-class-name: org.h2.Driver
    username: brosWarehouse
    password: brosWarehouse
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        trace: true
#        web-allow-others: true
#        web-admin-password: 123456


# Server setting ==================
server:
  port: 8888
  servlet:
    context-path: /
    session:
      timeout: 36000
  ssl:
    enabled: false
