CREATE TABLE BROS_WAREHOUSE (
  ID                VARCHAR(30) PRIMARY KEY
  , CREATED_BY      VARCHAR(30)
  , CREATED_DATE    DATETIME
  , UPDATED_BY      VARCHAR(30)
  , UPDATED_DATE    DATETIME

  , PHONE_NUMBER VARCHAR(255)
  , ADDRESS VARCHAR(2000)
  , NOTE VARCHAR(2000)
);